### ISSUE TITLE
Kanban project issue

### ISSUE THREAD

**Issue by Ezzywealth** [Ezzywealth/capstone-module2#83]
https://github.com/users/Ezzywealth/projects/4
This team has just 2 people in it.

**Comment by julie-ify** [comment]
## Hi @Ezzywealth,

Good job so far!

## Highlights!
- Descriptive pull request ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] Kindly add the other team member to this repo.

- [ ] You have not assigned any of your tasks. Kindly choose who would be Student A ans Student B and ensure all tasks are assigned based on that, including the group tasks.

  Your tasks should look like the image below when properly assigned.

  ![andre-assigned](https://user-images.githubusercontent.com/81468675/217018141-3b46fae9-b1a7-4f44-9819-1e924c1f9080.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by huseyinbiyik** [comment]
Hi @Ezzywealth and @aubinleyoung,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)

 ## Highlights
- PR description is descriptive 👌

 ## Required Changes ♻️
- As the previous review requested please ensure that all the tasks are assigned properly. 
<img width="421" alt="Screenshot 2023-02-06 at 7 33 29 PM" src="https://user-images.githubusercontent.com/25887253/217029301-35c2d2ef-da5e-40c7-be33-cb100921fc15.png">


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Hi @aubinleyoung and @Ezzywealth,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
